#!/usr/bin/env python3
"""Sync Shadowverse: Evolve cards from the official EN website.

This script scrapes:
- https://en.shadowverse-evolve.com/cards/
- /cards/searchresults/?expansion=...
- /cards/searchresults_ex?expansion=...&view=image&page=N

And writes:
- assets/www/data/shadowverse-evolve-card-catalog.csv
- assets/www/data/cards-data.js
"""

from __future__ import annotations

import csv
import html
import json
import re
import sys
import urllib.parse
import urllib.request
from pathlib import Path

BASE_URL = "https://en.shadowverse-evolve.com"
CARDS_URL = f"{BASE_URL}/cards/"

CARD_ENTRY_RE = re.compile(
    r'<a href="/cards/\?cardno=([^"&]+)[^"]*"><img src="([^"]+)"[^>]*alt="([^"]*)"',
    re.IGNORECASE,
)
EXPANSION_RE = re.compile(r"/cards/searchresults/\?expansion=([A-Za-z0-9\-]+)")
MAX_PAGE_RE = re.compile(r"max_page\s*=\s*(\d+)")


def fetch_text(url: str) -> str:
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Mozilla/5.0 (compatible; SVE-Catalog-Sync/1.0)",
            "Accept-Language": "en-US,en;q=0.9",
        },
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read().decode("utf-8", errors="replace")


def absolute_url(url: str) -> str:
    return urllib.parse.urljoin(BASE_URL, html.unescape(url))


def parse_entries(fragment_html: str) -> list[dict[str, str]]:
    entries: list[dict[str, str]] = []
    for code_raw, src_raw, name_raw in CARD_ENTRY_RE.findall(fragment_html):
        code = html.unescape(code_raw).strip()
        name = html.unescape(name_raw).strip()
        art_url = absolute_url(src_raw.strip())
        if not code:
            continue
        entries.append(
            {
                "Card Name": name,
                "Card Code": code,
                "Copies Possessed (out of 3)": "0",
                "Promo Obtain Source (if PR in code)": "",
                "Art URL": art_url,
            }
        )
    return entries


def card_sort_key(code: str) -> tuple[str, str]:
    parts = code.split("-", 1)
    set_code = parts[0] if parts else ""
    suffix = parts[1] if len(parts) > 1 else ""
    m = re.match(r"([A-Za-z]+)?(\d+)?", suffix)
    if not m:
        return (set_code, suffix)
    prefix = m.group(1) or ""
    num = int(m.group(2)) if m.group(2) else -1
    return (set_code, f"{prefix:>6}{num:06d}")


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    data_dir = repo_root / "assets" / "www" / "data"
    csv_path = data_dir / "shadowverse-evolve-card-catalog.csv"
    cards_data_js_path = data_dir / "cards-data.js"
    card_type_cache_path = data_dir / "shadowverse-cardtype-cache.json"

    print(f"[sync] Fetching expansion list from {CARDS_URL}")
    cards_html = fetch_text(CARDS_URL)
    expansions = sorted(set(EXPANSION_RE.findall(cards_html)))
    if not expansions:
        raise RuntimeError("No expansions found on official cards page.")
    print(f"[sync] Found {len(expansions)} expansion query keys.")

    cards_by_code: dict[str, dict[str, str]] = {}
    for exp in expansions:
        encoded_exp = urllib.parse.quote(exp, safe="")
        page1_url = f"{BASE_URL}/cards/searchresults/?expansion={encoded_exp}&view=image"
        print(f"[sync] Expansion {exp}: page 1")
        page1_html = fetch_text(page1_url)
        page_entries = parse_entries(page1_html)
        max_page_match = MAX_PAGE_RE.search(page1_html)
        max_page = int(max_page_match.group(1)) if max_page_match else 1
        for row in page_entries:
            cards_by_code[row["Card Code"]] = row

        for page in range(2, max_page + 1):
            ex_url = (
                f"{BASE_URL}/cards/searchresults_ex?expansion={encoded_exp}&view=image&page={page}"
            )
            print(f"[sync] Expansion {exp}: page {page}/{max_page}")
            ex_html = fetch_text(ex_url)
            for row in parse_entries(ex_html):
                cards_by_code[row["Card Code"]] = row

    rows = sorted(cards_by_code.values(), key=lambda r: card_sort_key(r["Card Code"]))
    print(f"[sync] Parsed unique cards: {len(rows)}")

    fieldnames = [
        "Card Name",
        "Card Code",
        "Copies Possessed (out of 3)",
        "Promo Obtain Source (if PR in code)",
        "Art URL",
    ]
    data_dir.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"[sync] Wrote CSV: {csv_path}")

    card_types: dict[str, str] = {}
    if card_type_cache_path.exists():
        try:
            card_types = json.loads(card_type_cache_path.read_text(encoding="utf-8"))
        except Exception:
            card_types = {}

    csv_text = csv_path.read_text(encoding="utf-8")
    csv_text = csv_text.replace("`", "\\`").replace("${", "\\${")
    cards_data_js = (
        "// Auto-generated by tool/sync_official_cards.py\n"
        f"window.SVE_CSV_DATA = `{csv_text}`;\n"
        f"window.SVE_CARDTYPE_DATA = {json.dumps(card_types, ensure_ascii=False)};\n"
    )
    cards_data_js_path.write_text(cards_data_js, encoding="utf-8")
    print(f"[sync] Wrote embedded data: {cards_data_js_path}")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"[sync] ERROR: {exc}", file=sys.stderr)
        raise
